all:
	ocamlc -o all.out batteries.mli batteries.ml ha1.mli ha1.ml ha2.mli ha2.ml ha3.mli ha3.ml

ha1:
	ocamlc -o ha1.out batteries.mli batteries.ml ha1.mli ha1.ml

ha2:
	ocamlc -o ha2.out batteries.mli batteries.ml ha2.mli ha2.ml

ha3:
	ocamlc -o ha3.out batteries.mli batteries.ml ha3.mli ha3.ml

clean:
	rm *.cmo *.cmi *.out
