basics:
	ocamlc -o threadingBasics.out -thread -I +threads unix.cma threads.cma Threading_Basics.mli Threading_Basics.ml Threading_Basics_Test.ml

more:
	ocamlc -o moreThreads.out -thread -I +threads unix.cma threads.cma More_Threads.mli More_Threads.ml

clean:
	rm *.cmo *.cmi *.out
