ha1:
	ocamlc -o ha1.out ha1.mli ha1.ml

ha2:
	ocamlc -o ha2.out ha2.mli ha2.ml

ha3:
	ocamlc -o ha3.out ha3.mli ha3.ml

ha6:
	ocamlc -o ha6.out batteries.ml ha6.mli ha6.ml

all:
	make ha1 
	make ha2 
	make ha3 
	make ha6

clean:
	rm *.cmo *.cmi *.out
